### ISSUE TITLE
Use supported google.golang.org/protobuf module as dependency

### ISSUE THREAD

**Issue by julio-lopez** [google/fswalker#36]
Replace deprecated `github.com/golang/protobuf` dependency with `google.golang.org/protobuf` module, which is actively supported.

- https://github.com/golang/protobuf
- https://pkg.go.dev/github.com/golang/protobuf
- https://pkg.go.dev/google.golang.org/protobuf

**Comment by aaomidi** [comment]
Partially done with #39
